### ISSUE TITLE
Can't install zc.libstorage 1.2.0 with pyenv

### ISSUE THREAD

**Issue by iuriguilherme** [zopefoundation/zc.zlibstorage#14]
### What I did:

My project has zc.libstorage v1.2.0 [as a requirement](https://github.com/iuriguilherme/iacecil/blob/e0581324c7f4468d6ecc49bc14f8fb6e2cd64329/setup.py)  

### What I expect to happen:

Install my project as an editable package (for example `pip install -e git+pathtoproject.etc`)  

### What actually happened:

```
Error processing line 1 of /home/iuri/.local/share/virtualenvs/iacecil.0.2-abcdefgh/lib/python3.9/site-packages/zc.zlibstorage-1.2.0-py3.9-nspkg.pth:

  Traceback (most recent call last):
    File "/home/iuri/.pyenv/versions/3.9.2/lib/python3.9/site.py", line 169, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
    File "<frozen importlib._bootstrap>", line 562, in module_from_spec
  AttributeError: 'NoneType' object has no attribute 'loader'

Remainder of file ignored
Error processing line 1 of /home/iuri/.local/share/virtualenvs/iacecil.0.2-abcdefgh/lib/python3.9/site-packages/zc.zlibstorage-1.2.0-py3.9-nspkg.pth:

  Traceback (most recent call last):
    File "/home/iuri/.pyenv/versions/3.9.2/lib/python3.9/site.py", line 169, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
    File "<frozen importlib._bootstrap>", line 562, in module_from_spec
  AttributeError: 'NoneType' object has no attribute 'loader'

Remainder of file ignored
```

### What version of Python and Zope/Addons I am using:

Python 3.9.2 from a local pyenv install (not root) in a Debian 9.13 Stretch, other installed packages:

'zc.lockfile==2.0', 'zc.zlibstorage==1.2.0', 'zconfig==3.6.0', 'zodb==5.7.0', 'zodbpickle==2.4', "zope.interface==5.5.0

**Comment by d-maurer** [comment]
Iuri Guilherme wrote at 2022-10-22 11:17 -0700:
> ...
>Error processing line 1 of /home/iuri/.local/share/virtualenvs/iacecil.0.2-abcdefgh/lib/python3.9/site-packages/zc.zlibstorage-1.2.0-py3.9-nspkg.pth:
>
>  Traceback (most recent call last):
>    File "/home/iuri/.pyenv/versions/3.9.2/lib/python3.9/site.py", line 169, in addpackage
>      exec(line)
>    File "<string>", line 1, in <module>
>    File "<frozen importlib._bootstrap>", line 562, in module_from_spec
>  AttributeError: 'NoneType' object has no attribute 'loader'
>
>Remainder of file ignored
>Error processing line 1 of /home/iuri/.local/share/virtualenvs/iacecil.0.2-abcdefgh/lib/python3.9/site-packages/zc.zlibstorage-1.2.0-py3.9-nspkg.pth:
>
>  Traceback (most recent call last):
>    File "/home/iuri/.pyenv/versions/3.9.2/lib/python3.9/site.py", line 169, in addpackage
>      exec(line)
>    File "<string>", line 1, in <module>
>    File "<frozen importlib._bootstrap>", line 562, in module_from_spec
>  AttributeError: 'NoneType' object has no attribute 'loader'
>
>Remainder of file ignored
>```
>
>### What version of Python and Zope/Addons I am using:
>
>Python 3.9.2 from a local pyenv install (not root) in a Debian 9.13 Stretch, other installed packages:

Potentially, it is not Python 3.9 compatible.
The metadata says: Python 2.7 and Python 3.4-3.6.

**Comment by iuriguilherme** [comment]
Disregard this, it was a problem in my virtual environment unrelated to this package. Thanks for the answer.

**Comment by mgedmin** [comment]
> The metadata says: Python 2.7 and Python 3.4-3.6.

The metadata in git master claims support for Python 3.5-3.10.  There were no code changes needed for that, hence making new release didn't seem important, presumably.
